### ISSUE TITLE
installation stuck

### ISSUE THREAD

**Issue by sevku** [stuomas/delicious-sddm-theme#3]
> SDDM configuration file /etc/sddm.conf does not exist, do you want to create it based on current configuration?

Stuck at this question, can answer it endlessly, nothing happens

**Comment by stuomas** [comment]
Hi, probably it is not able to write the file to your /etc/sddm.conf.

For some reason I have set the function to discard any output so it won't tell about errors:
```
function createConfig {
    sddm --example-config | sudo tee $CFG > /dev/null
    echo "Configuration file created in $CFG"
}
```
You can remove the `> /dev/null` part to see output.
